export const productionMetrics = [
  {
    id: "prod-proxmox",
    title: "Proxmox Host",
    summary: "Online",
    status: "Healthy",
    statusColor: "#22c55e",
    details: [
      { label: "CPU", value: "28%" },
      { label: "Memory", value: "52%" },
      { label: "Storage", value: "44%" },
      { label: "Uptime", value: "18d 7h" },
    ],
  },
  {
    id: "prod-vms",
    title: "Virtual Machines",
    summary: "5 Running",
    status: "Healthy",
    statusColor: "#22c55e",
    details: [
      { label: "Running", value: "5" },
      { label: "Stopped", value: "0" },
      { label: "Snapshots", value: "3" },
      { label: "Backups", value: "Current" },
    ],
  },
  {
    id: "prod-homeassistant",
    title: "Home Assistant",
    summary: "Online",
    status: "Healthy",
    statusColor: "#22c55e",
    details: [
      { label: "Automations", value: "86" },
      { label: "Devices", value: "64" },
      { label: "Entities", value: "740" },
      { label: "Uptime", value: "18d 6h" },
    ],
  },
  {
    id: "prod-frigate",
    title: "Frigate / Cameras",
    summary: "20 / 20 Online",
    status: "Recording",
    statusColor: "#22c55e",
    details: [
      { label: "Cameras", value: "20 / 20" },
      { label: "Recording", value: "Active" },
      { label: "AI Detection", value: "Active" },
      { label: "Coral TPU", value: "Healthy" },
      { label: "Storage", value: "64%" },
    ],
  },
  {
    id: "prod-mqtt",
    title: "MQTT / IoT",
    summary: "Connected",
    status: "Healthy",
    statusColor: "#22c55e",
    details: [
      { label: "Broker", value: "Online" },
      { label: "Clients", value: "34" },
      { label: "Messages/sec", value: "128" },
      { label: "IoT Devices", value: "42" },
    ],
  },
  {
    id: "prod-resources",
    title: "Host Resources",
    summary: "Normal",
    status: "Healthy",
    statusColor: "#22c55e",
    details: [
      { label: "CPU", value: "28%" },
      { label: "Memory", value: "52%" },
      { label: "Storage", value: "44%" },
      { label: "Network", value: "186 Mbps" },
    ],
  },
];